### PR TITLE
Feature/gulp

### PR DESCRIPTION
**Pull request by nahuelsotelo**
As we talked with @danderu via Slack, I replaced webpack for gulp, since webpack wasn't working.
Besides, I think Gulp is easier here, in a non React environment. 

After `npm install`, just run `gulp` to start the project

cc/ @nucliweb

### CODE REVIEW

**Comment by nahuelsotelo** [comment]
I already configure autoprefixer, scss-lint, sourcemaps and browsersync.

**Comment by danderu** [comment]
If it's easier for everyone to understand, and it works :) I have nothing to say. I prefer the configuration approach of Webpack over the codification in a gulpfile, but it's just an implementation detail.

**Comment by danderu** [comment]
@nahuelsotelo I've pulled your PR, followed the instructions, typed `gulp` and I can't see anything in the browser :(

On the other hand, when you say that the webpack version isn't working, what do you mean? I've got HMR with js and css, the only thing that is not replaced is html

**Comment by danderu** [comment]
We'll close it, since it already works with Webpack. Checked with @nahuelsotelo

**Pull request closed without merging**
